--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t dbaxy770928/node-server ."
      - "docker tag dbaxy770928/node-server dbaxy770928/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=dbaxy770928 --password=Symantec@123b "
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push dbaxy770928/node-server:latest"
      - "printf '[{"name":"node-server","imageUri":"dbaxy770928/node-server:latest"}]'  > imagedefinitions.json"
artifacts:
    files: imagedefinitions.json
version: 0.2

